# Generated by Django 4.2.3 on 2023-08-09 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockControl',
            fields=[
                ('weekday_one_hour', models.IntegerField(default=0)),
                ('weekday_two_hour', models.IntegerField(default=0)),
                ('weekday_three_hour', models.IntegerField(default=0)),
                ('weekend_one_hour', models.IntegerField(default=0)),
                ('weekend_two_hour', models.IntegerField(default=0)),
                ('weekend_three_hour', models.IntegerField(default=0)),
                ('storeID', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('weekday_one_hour', models.IntegerField(default=0)),
                ('weekday_two_hour', models.IntegerField(default=0)),
                ('weekday_three_hour', models.IntegerField(default=0)),
                ('weekend_one_hour', models.IntegerField(default=0)),
                ('weekend_two_hour', models.IntegerField(default=0)),
                ('weekend_three_hour', models.IntegerField(default=0)),
                ('date_of_purchase', models.DateTimeField(primary_key=True, serialize=False)),
                ('price_of_order', models.FloatField(default=0)),
                ('payment_method', models.CharField(blank=True, max_length=200)),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.stockcontrol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouponsTally',
            fields=[
                ('couponID', models.AutoField(primary_key=True, serialize=False)),
                ('coupontype', models.IntegerField(default=0)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('oct_number', models.CharField(default=0, max_length=200)),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.stockcontrol')),
            ],
        ),
    ]
