# Generated by Django 4.2.3 on 2023-08-09 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='date_of_purchase',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
